# NeON Build File (http://github.com/c4s4/neon)

extends:
- c4s4/build/golang.yml

properties:
  NAME:     'roman'
  VERSION:  '1.0.0'
  RUN_ARGS: ['1', '2', '3', '12', '47', '727', '1999', '2019', '3457', '4999']

targets:

  ask:
    doc: 'Ask for the number to convert'
    steps:
    - prompt:  'Number'
      to:      number
    - $: ['go', 'run', 'roman.go', =number]
